// Types for the module generated by vite.catalog.ts.
declare module 'virtual:catalog-meta' {
  export const vocab: import('#lib/catalog/types.js').VocabData;
  export const licenses: { id: string; name: string; short_name?: string; purpose: string }[];
  export const datasetCount: number;
}
